### ISSUE TITLE
Error with R 3.4

### ISSUE THREAD

**Issue by danielcanueto** [thomasp85/shinyFiles#57]
Hi Thomas,

When loading a Shiny app with 3.4, I get this message:

Warning in body(fun) : argument is not a function
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.

When I click on the ShinyFiles button to save a variable, no folder appears on the menu, and when I close the window the app crashes with this message:

Warning: Error in [[: subscript out of bounds
Stack trace (innermost first):
    58: fileGet
    57: do.call
    56: observerFunc
     1: runApp

ATB

Daniel

**Comment by danielcanueto** [comment]
Hi Thomas,

When loading a Shiny app with 3.4, I get this message:

I know have a better idea of the problem. The package cannot deal well with R 3.4 in Windows (in Linux it can, and in Windows deals well with R 3.3). If the 'volumes' variable given here:

 shinyFileSave(input, "save", roots=volumes, session=session)
    fileinfo <- parseSavePath(volumes, input$save)

 is something like 'R.home()', it works well, but if it is something like "C:/" it cannot handle it.

I hope this info helps solve the bug. I wanted to send an application note today, but I will have to delay it until the problem is solved.

ATB

Daniel

**Comment by thomasp85** [comment]
Hi Daniel

I'm sorry this regression has caused a delay in your submission. Unfortunately shinyFiles is quite low in my priority list (all of my projects are done in my spare time) and I will not be able to look into this right know. At least a month will go before I can attend it. Sorry about this but I just want to be upfront about it.

Best
Thomas

**Comment by thomasp85** [comment]
Can I get you to create a minimal app that shows the behaviour you're reporting

**Comment by lecrabe** [comment]
Hi Thomas
I have exactly the same problem  (functioning in LINUX 3.4 and Windows <= 3.3 but staying in limbo for Windows 3.4), not resolved that I know of. Volumes dont get read or something.

A minimal app :

library(shiny)
library(shinyFiles)

shinyApp(
  ui = fluidPage(
    mainPanel(
      shinyFilesButton(id = 'file',
                       label = "Input",  
                       title = "Browse", 
                       multiple = FALSE),      
      textOutput('fileout')
    )
  ),
  server = function(input, output,session) {
    shinyFileChoose(input,
                    'file',
                    filetype = c('csv'),
                    roots = c('Home' = Sys.getenv("HOME")),
                    session = session,
                    restrictions = system.file(package = 'base')
                    )
    output$fileout <- renderPrint({
      req(input$file)
      "file read"
      })
  }
)

**Comment by goreaditya** [comment]
Hi Thomas!

A similar issue

```
library(shiny)
library(shinyFiles)

shinyApp(
ui = fluidPage(
mainPanel(
shinyFilesButton(id = 'file',
label = "Input",
title = "Browse",
multiple = FALSE),
textOutput('fileout')
)
),
server = function(input, output,session) {
shinyFileChoose(input,
'file',
filetype = c('csv'),
roots = c('C:' = "C:/"),
session = session,
restrictions = system.file(package = 'base')
)
output$fileout <- renderPrint({
req(input$file)
"file read"
})
}
)
```

I get this warning
Listening on http://127.0.0.1:4182
```
Warning in file.info(files) :
  cannot open file 'C:/hiberfil.sys': The process cannot access the file because it is being used by another process
Warning in file.info(files) :
  cannot open file 'C:/pagefile.sys': The process cannot access the file because it is being used by another process
Warning in file.info(files) :
  cannot open file 'C:/Recovery': Access is denied
Warning in file.info(files) :
  cannot open file 'C:/swapfile.sys': The process cannot access the file because it is being used by another process
Warning in file.info(files) :
  cannot open file 'C:/System Volume Information': Access is denied
```

The reason for the function to give these warnings is because R v3.4.1 has a different way of implementing `file.info()` which results in warnings. The function you might want to modify is `fileGetter`.

-Aditya

**Comment by sylvainschmitt** [comment]
I think I have a user of my package `SSDM` having the same issue (I use `shinyFiles` as a dependency): https://github.com/sylvainschmitt/SSDM/issues/8#issuecomment-329098382

**Comment by mrjoh3** [comment]
Using windows and R3.4 I have the same issue, but have found that shortened file paths do work (not sure why). So instead of `I:\My Documents\My Pictures` use `I:/MYDOCU~1/MYPICT~1`. You can use the example [here](https://code.adonline.id.au/short-paths-via-powershell/) to get the shortened paths.

This is clearly just a temporary work-around until a proper solution is found.

**Comment by sravel** [comment]
Hi 
I have the same issue with R 3.5 on Windows 7.
I'm not expert on R so can you explain how modify fileGetter to solve error?
Thanks

**Comment by thercast** [comment]
I've done some research and testing on a Windows VM running R 3.4.1, using the example app @goreaditya provided above. I've search high and low for a solution and have come up empty.  But I think there is a path forward that will hopefully be future-proof (albeit will require a bit of refactoring):

* I think the [`fs`](https://fs.r-lib.org/) package would offer a cleaner way of obtaining file attributes, specifically using `fs::file_info()` instead of `base::file.info()`.  I verified that `file_info()` returns an error if it tries to read a file that it is not permitted to access.  This is in direct contrast to `base::file.info()` which sends the warnings seen above but still returns a 1-row data frame with certain columns (`mtime`, `ctime`, `atime`) set to missing.  I actually prefer returning an error, leading me to my next point.
* In my opinion, any file/directory that cannot be accessed (due to permission issues, etc) should not appear in the list of files returned to the user.  
* I propose that we detect which files within the directory currently viewed result in the permissions error (either via `tryCatch` or `purrr::safely` if having `purrr` as a depedency is permitted).  Then only the files that pass the detection would proceed further down the processing in `fileGetter`.

Other than modifying some of the bits in `fileGetter`, I think the rest of the package code could remain as-is.  @thomasp85 do you have any concerns about this approach?

**Comment by thomasp85** [comment]
No - I think it sounds perfect!

Thanks!

**Comment by thomasp85** [comment]
@thercast Are you on this?

**Comment by thomasp85** [comment]
I think we could avoid the added dependencies of `fs` (and `purrr`) by simply creating our own `file_info()` which wraps `file.info()` in a `suppressWarnings()` and gracefully fails if permission is denied

**Comment by thercast** [comment]
@thomasp85 Yes I had a fork going with the use of `fs` but it seems like diminishing returns all for this single issue.  Perhaps in future versions we can go that route if we run in to other barriers but for now I'll table that overhaul and use your suggesting of `suppressWarnings()` since technically the directories are still browse-able.

**Comment by thomasp85** [comment]
Great - once this is done I’ll submit to CRAN and we can have a talk about future directions for the package
