### ISSUE TITLE
Creating new folder crashes the app

### ISSUE THREAD

**Issue by keqiang** [thomasp85/shinyFiles#62]
Hi, 

While hitting the 'Enter' button successfully creates the folder, clicking the plus button crashes the app.

> Warning: Error in dir.create: invalid 'path' argument
Stack trace (innermost first):
    58: dir.create
    57: dirCreate
    56: observerFunc
     1: shiny::runApp

one more tiny issue is when the folder already exists, it fails silently without giving the user any prompt. It does log to the console a warning though.

**Comment by renedlog** [comment]
The problem seems to be in the dirCreator function.... 

```
150 dirCreator <- function(roots, ...) { 
151     function(name, path, root) { 
152         currentRoots <- if(class(roots) == 'function') roots() else roots 
153          
154         if (is.null(names(currentRoots))) stop('Roots must be a named vector or a function returning one') 
155          
156         location <- do.call('file.path', as.list(path)) 
157         location <- file.path(currentRoots[root], location, name) 
158          
159         dir.create(location) 
160     } 
161 } 
```
the variable path of dir.create is named location and what is causing the problem in the function seems to be the call:

`do.call('file.path', as.list(path)) `

I couldn't find a fix so far. In my opinion, the documentation of the code should be improved.
