### ISSUE TITLE
Please submit updates to CRAN

### ISSUE THREAD

**Issue by gwarnes-mdsol** [thomasp85/shinyFiles#72]
I ran into an error with the CRAN version of `shinyFiles` because the call to `data.frame` in `parseFilePaths` doesn't have `stringsAsFactors = FALSE`.  

This was corrected in #48, but the version on CRAN was released prior to it's acceptance.

**Comment by mjhelf** [comment]
I have the same problem with the CRAN version when trying to use shinyFiles inside a module - it works fine with the github version.
Can you please also bump the version number so that one can require the newest version as dependency for a packages? That would be great, because currently both, CRAN and github, are version 0.6.2..

Thanks for this great package!

**Comment by thomasp85** [comment]
Hi

I'm happy that people continue to find this package useful - unfortunately I simply do not have the time to maintain it for now. I've asked out on Twitter if anyone is interested in taking it over without any positive responses.

If anyone is willing to take the current development version to a CRAN release I'll be happy to assist but it won't happen without outside help

**Comment by mjhelf** [comment]
Hi Thomas, 

thanks for your reply!

I understand that maintenance is time consuming, and finding someone to take over that job may be difficult (and sorry, I can't do it...).

For now, could you maybe bump the version in the Description file on the github master branch so that it is easier to see which version is installed? I think these significant bug fixes warrant a new version number :)

**Comment by elinw** [comment]
Thomas,

Why don't you specifically ask some of the PR contributors as maintainers of the repository?  I don't necessarily think people know what is involved, which for something like changing the version number to 0.6.3 is pretty minimal.

**Comment by thercast** [comment]
@thomasp85 sorry for not getting back to you after my tweet back in March, but I am interested in doing what I can to assist.  I saw you received a note from Vincent (@vnijs) expressing support, so we might be able to team up and get this ready for a new CRAN release.

**Comment by thomasp85** [comment]
@thercast if you have access to a windows machine I would be happy if you could look into #57 - it seems to be a windows thing

**Comment by vnijs** [comment]
Since 0.7.0 is on CRAN I think this issue can be closed
